### Create http-client.env.json instead variables - many env`s

### Step 1. Get token
POST http://host.docker.internal:{{keycloak-port}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials &
client_id = {{client_id}} &
client_secret = {{client_secret}}

> {%
    client.test("Token request successful", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.hasOwnProperty("access_token"), "No access_token in response");
    });
    client.global.set("auth_token", response.body.access_token);
%}

### Step 2. Check Actuator and metrics
GET http://host.docker.internal:{{actuator-port}}/actuator/prometheus
Authorization: Bearer {{auth_token}}
Accept: text/plain;version=0.0.4;charset=utf-8

> {%
    client.test("Prometheus metrics available", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "text/plain", "Expected text/plain");
        client.assert(response.body.includes("jvm_memory_used_bytes"), "Metrics not found in body");
    });
%}
